name: e_lib_17_jose
version: 1.0.0+1
publish_to: none
description: Project Akhir
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  get: 4.6.5
  animations: ^2.0.11
  another_flutter_splash_screen:
  salomon_bottom_bar: ^3.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

