name: e_lib_17_jose
version: 1.0.0+1
publish_to: none
description: Project Akhir
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  get: 4.6.5
  animations: ^2.0.11
  another_flutter_splash_screen:
  date_time_picker: ^2.1.0
  flutter: 
    sdk: flutter
  sqflite: ^2.0.0
  expandable_text: ^2.3.0
  flutter_riverpod: ^1.0.3
  double_tap_to_exit: ^1.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21